### ISSUE TITLE
make this a Julia package?

### ISSUE THREAD

**Issue by tanmaykm** [JuliaComputing/NDSparseData.jl#2]
The repo needs to be renamed, to `NDSparseArrays` perhaps?
We could then retain `NDSparse` as the exported type, which seems nice.

**Comment by ViralBShah** [comment]
How about NDSparseData? Since we do want multiple data columns.

**Comment by tanmaykm** [comment]
Yes, sounds good.

**Comment by ViralBShah** [comment]
Renamed.
