### ISSUE TITLE
Vector indexing requires the indices to be sorted

### ISSUE THREAD

**Issue by pranavtbhat** [JuliaComputing/NDSparseData.jl#8]
```julia
a = NDSparse([1,2,3], [1,2,3], [1,2,3])
# NDSparse{Int64,Tuple{Int64,Int64}}:
# (1,1) => 1
# (2,2) => 2
# (3,3) => 3

a[[1,2,3], [1,2,3]]  # This works fine                      
# NDSparse{Int64,Tuple{Int64,Int64}}:
# (1,1) => 1
# (2,2) => 2
# (3,3) => 3

a[[2,1,3], [2,1,3]]   # Doesn't work
# NDSparse{Int64,Tuple{Int64,Int64}}:
# (2,2) => 2
# (3,3) => 3

a[[3,2,1], [3,2,1]]   # Doesn't work at all
NDSparse{Int64,Tuple{Int64,Int64}}:
```

I think the solution is to item-wise sort `idxs` [here](https://github.com/JuliaComputing/NDSparseData.jl/blob/master/src/NDSparseData.jl#L206) ?

**Comment by ViralBShah** [comment]
Cc @tanmaykm @shashi Would be great if you guys can also watch this repo.

**Comment by tanmaykm** [comment]
Sorting just `idxs[1]` for call to `range_estimate` also works in this case.
Here: https://github.com/JuliaComputing/NDSparseData.jl/blob/e86721e0851c651e6bdd7ebf4a13caae1f7b84c1/src/NDSparseData.jl#L216

**Comment by tanmaykm** [comment]
Sorry, that doesn't work in all cases.

`row_in` uses `searchsorted`, so yes, `idxs` needs to be sorted.
